### ISSUE TITLE
Client Version

### ISSUE THREAD

**Issue by RARgames** [ReSpeak/SimpleBot#2]
From where the bot is getting client version?
Is it possible to easily change it?

**Comment by Flakebi** [comment]
Hi, the bot does not explicitly set it so the default version of tsclientlib is used here: [tsclientlib/src/lib.rs:L814](https://github.com/ReSpeak/tsclientlib/blob/4f3257abe1e6bfb359a692908a0684cd8bb6b5a2/tsclientlib/src/lib.rs#L814)

If you want to change it, you can add these lines to the connection options (untested code):
The data are taken from the Versions we keep here: https://github.com/ReSpeak/tsdeclarations/blob/master/Versions.csv
```rust
    .version(Version::Custom {
        platform: "Windows".into(),
        version: "3.3.0 [Build: 1559307127]".into(),
        signature: base64::decode("His8U9cnGKfL1f93iCm/9H5TSmtRFBBkcPW2czbcY7bA71IvQrXB+nxx7dNqilVxPZxqfB7yuKieGdA6kO+FBA==").unwrap(),
    })
```

https://github.com/ReSpeak/SimpleBot/blob/4c13b3768c862a7c60f5ffc98d73ee953913a67b/src/main.rs#L273

I also pushed an update that will use the 3.3.0 version by default and should be available soon.

Update: Seems like the server currently has some problems accepting the uploads, I will try again tomorrow.

Update 2: The builds succeed now, nightly binaries are uploading :)

**Comment by RARgames** [comment]
Thanks a lot,

I have no prior rust experience, but I figured out that in order to build I need to add:
Version to 
`use tsclientlib::{
	ConnectOptions, Connection, ConnectionLock, DisconnectOptions, InvokerRef,
	MessageTarget, Reason, Version
};`
and 
something with use base64, but I cannot get it working right now

**Comment by Flakebi** [comment]
Ah you’re right, nice that you figured it out.
For base64, it should work if you add it to the dependencies section here:
```toml
base64 = "0.10"
```

https://github.com/ReSpeak/SimpleBot/blob/4c13b3768c862a7c60f5ffc98d73ee953913a67b/Cargo.toml#L10
