### ISSUE TITLE
Default channel

### ISSUE THREAD

**Issue by RARgames** [ReSpeak/SimpleBot#3]
I guess that it is easy to set default_channel by adding a code snippet into main.rs and it is last thing that I need.
I would be more than happy if you can help me with this.

It is probably as simple as my last question. (I've created extra issue as someone may find this useful later)

**Comment by Flakebi** [comment]
That’s more complicated as tsclientlib currently does not support setting a default channel.
I will try to add it in the next few days, then it should be as easy as setting the version.

**Comment by Flakebi** [comment]
Okay, setting a default channel works now.
You probably need to run `cargo update` to update the tsclientlib.
You can now add a channel to the ConnectOptions:
```rust
let opts = ConnectOptions::new("localhost").channel("Default Channel".to_string());
let opts = ConnectOptions::new("localhost").channel("Default Channel/Nested".to_string());
let opts = ConnectOptions::new("localhost").channel_id(ChannelId(2));
// ChannelId(2) is equivalent to "/2"
```

**Comment by RARgames** [comment]
Thanks, it works!
